const fs = require('fs')

exports.randomCantadas = [
   "Te quero de 69 jeitos diferentes.", 
   "Não apague o meu fogo, queime comigo.", 
   "Eu e minha língua queremos saborear você sem pressa.", 
   "Me esquentando com os lençóis, mas queria mesmo era tá me esquentando com você.", 
   "As tentações como você, merecem pecados como eu.", 
   "Meu deslize favorito é o seu corpo no meu.", 
   "Dizem que fazer amor prolonga a vida, vem cá para eu te fazer imortal.", 
   "Vale massagem! Mas é como diria o filósofo, o erro é achar que para por aí.", 
   "Mais bonita que sua boca, somente ela nos meus lábios… Não disse quais.", 
   "Eu preciso conversar muito sério com você, mas tem que ser sem roupa.", 
   "Não sou de apoiar casal, mas olha eu e você, hein... Casalzão!", 
   "O que eu penso em fazer com você é um pecado, mas por isso eu aceito ir pro inferno sem reclamar.", 
   "Nada contra a sua cama, mas acho que você deveria dormir na minha.", 
   "Nosso encaixe pode ser perfeito, podemos testar isso mais tarde na minha cama.", 
   "Um toque seu é o suficiente para a gente começar a realizar todos os meus desejos mais intensos…", 
   "Quero cuidar do meu namorado para ele não ficar doente nunca… É só chá por cima de chá.", 
   "Hoje eu queria cometer um crime, roubar uns beijos teus. O que vem depois ainda ainda é segredo.", 
   "Ouvi dizer que hoje o clima esquenta, sabe dizer se é verdade e se topa me ajudar nisso?", 
   "Estou tão cansada hoje que só queria sentar em você.", 
   "Basta um toque seu em meu corpo para que todos meus desejos com você comecem a se tornar a minha realidade.", 
   "Sua boca valeu o preço de perder todo o sossego que eu tinha.", 
   "Você gostaria de passar a noite vendo estrelas? Conheço um motel que tem 5.", 
   "Eu, você, Netflix, uma cama e um dia chuvoso. Bora? 💭", 
   "Sabe o que te deixaria mais e feliz e também ficaria bem em você?  Eu.", 
   "Quer fazer um teste para os bombeiros apagando meu fogo hoje?", 
   "Acho que eu e você nos encaixamos perfeitamente, se é que você me entende.", 
   "Tô aqui chupando uma bala mas poderia ser você, topa?", 
   "Tentação é quando a mente proíbe e o corpo desobedece, posso te mostrar na prática.", 
   "E aí, rola suas pernas aquecendo minhas orelhas?", 
   "Sobre você, eu não diria que tenho uma mente suja, mas uma imaginação quente.", 
   "Vale replay: já que na primeira vez foi bom, esse ticket é um convite para repetir os beijos.", 
   "Só me confirma seu nome mesmo... É que eu preciso saber o que é que eu vou gritar hoje à noite.", 
   "Andei te observando e percebi que você tem todos os pré-requisitos para vir tirar a minha roupa… topa?", 
   "Quando eu abrir seu zíper, vai ser como as portas do paraíso se abrindo para nós dois. Topa?", 
   "Que cor de roupa preciso usar na virada de ano pra você vir tirar?",
   "Não sou o Papai Noel, mas poderia te proporcionar uma noite feliz... ",
   "Meu Deus, estou sem ar, me ajuda! Acho que você precisa fazer respiração boca-boca para me salvar... ",
   "Acredita em amor à primeira vista, ou devo passar por você de novo?",
   "Deve haver algo errado com meus olhos. Eu não posso tirá-los de você.", 
   "Se você fosse uma música, você seria aquela que não sai da minha cabeça",
   "Você não é a Monalisa, mas é uma obra de arte.",
   "Se as estrelas fossem tão lindas como você, eu passaria as noites em claro.",
   "Se as estrelas fossem tão lindas como você, eu passaria as noites em claro.",
   "Meu coração sempre capota na curva do seu sorriso.",
   "Você é a primeira maravilha do meu mundo.",
   "Sabe com qual signo o meu combina? Com o seu!",
   "Me chama de tabela periódica e diz que está rolando uma química entre nós.",
   "Você não é o Death Note, mas atingiu meu coração em 40 segundos.",
   "Tá vendo aquele cara ali? Pois é, ele tá perguntando se você quer ficar comigo.",
   "Me empresta uma foto sua para eu mostrar para o Papai Noel o que quero de presente!"
   ,"Vamos ao cartório para eu passar o meu coração para o seu nome.",
   "Aposto um beijo que você vai me dar um fora.", 
   "Suas pernas não doem de fugir dos meus sonhos todas as noites, meu amor?", 
   "Me chame de urna eletrônica e me dê seu voto de confiança."
]